import 'package:get/get.dart';
import 'constants.dart' as c;

class Language extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      c.homeTabRes: "SIRKL",
      c.callsTabRes: "Calls",
      c.groupsTabRes: "Groups",
      c.chatsTabRes: "Inbox",
      c.profileTabRes: "Profile",
      c.connectYourWalletRes: "Connect your wallet",
      c.talkWithRes: "Talk with other wallets and your NFT groups",
      c.getStartedRes: "Get Started",
      c.myNFTCollectionRes: "My NFT Collection",
      c.editProfileRes: "• Edit profile",
      c.contactUsRes: "• Contact us",
      c.logoutRes: "• Logout",
      c.noGroupYetRes: "No Group Yet",
      c.errorFindingCollection: "You don't find your collection here and you own the NFT",
      c.addGroupRes: "+ Add the group chat to the list",
      c.newMessageRes: "New Message",
      c.toRes: "To",
      c.contactsRes: "Contacts",
      c.writeHereRes: "Write here...",
      c.notificationsRes: "Notifications",
      c.errorRes: "Error",
      c.errorWalletAlreadyUsedRes: "This user already exists. Try to sign in instead.",
      c.noDescYetRes: "No description yet. Edit your profile to tell a little bit more about you.",
      c.addToMySirklRes: "• Add to My Sirkl",
      c.removeOfMySirklRes: "• Remove from My Sirkl",
      c.reportRes: "• Report",
      c.sendAMessageRes: "• Send a message",
      c.userAddedToSirklRes: "@user is now added to your Sirkl",
      c.userRemovedofSirklRes: "@user is now removed from your Sirkl",
      c.dontHaveNftRes: "You don't have any NFT",
      c.createSecurePasswordRes: "Create a secure password",
      c.atLeast6CharsRes: "At least 6 characters long",
      c.includeNumberRes: "Include a number",
      c.includeSpecialChar: "Include a special character",
      c.createPasswordRes: "Create your password",
      c.confirmPasswordRes: "Confirm your password",
      c.passwordsNotIdentical: "password are not identical",
      c.signinRes: "Sign In",
      c.thisIsSeedPhraseRes: "This is your seed phrase",
      c.keepItRes : "Keep it safe offline, it's the only way to recover your account",
      c.dontScreenRes: "No Screenshot",
      c.writeItRes: "Write It Down",
      c.dontShareRes: "Don't Share it",
      c.onlyTimeRes: "It's The Only Time You Will See It",
      c.notedSeedPhraseRes: "I have noted my seed phrase offline",
      c.copyItRes: "Copy your seed phrase, it's the only time you will see it",
      c.signupRes: "Sign Up",
      c.welcomeBackRes: "Welcome Back!",
      c.passwordRes: "Password",
      c.forgotPasswordRes: "Forgot password?",
      c.recoverPasswordRes: "Recover My Password",
      c.loginRes: "Log In",
      c.enterSeedPhraseRes: "Enter your seed phrase",
      c.seedPhraseGivenAtCreationRes: "It has been given to you when you were creating your account"
    }
  };

}