name: sirkl
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_portal: ^1.0.0
  image_gallery_saver: 1.7.0
  image_picker: ^0.8.6
  jiffy: ^5.0.0
  lottie: ^1.0.1
  meta: ^1.3.0
  path_provider: ^2.0.9
  photo_manager: ^2.0.1
  firebase_analytics: ^10.2.0
  photo_view: ^0.14.0
  share_plus: ^6.3.2
  shimmer: ^2.0.0
  stream_chat_flutter_core: ^6.1.0
  synchronized: ^3.0.0
  thumblr: ^0.0.4
  video_player: ^2.4.5
  get: ^4.6.3
  get_storage: ^2.0.3
  nice_buttons: ^0.0.2
  flutter_svg: ^1.1.5
  material_floating_search_bar: ^0.3.7
  azlistview: ^2.0.0
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.5
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  images_picker: ^1.2.11
  simple_s3: ^0.3.2
  cached_network_image: ^3.2.2
  infinite_scroll_pagination: ^3.2.0
  timeago: ^3.3.0
  intl: ^0.17.0
  tiny_avatar: ^0.0.3
  chewie: ^1.3.4
  collection: ^1.15.0
  contextmenu: ^3.0.0
  dart_vlc: ^0.4.0
  desktop_drop: ^0.3.3
  diacritic: ^0.1.3
  dio: ^5.1.1
  ezanimation: ^0.6.0
  file_picker: ^5.2.5
  file_selector: ^0.9.0
  web3dart: ^2.4.1
  slider_button: ^2.0.0
  agora_rtc_engine: ^5.3.1
  permission_handler: ^9.2.0
  flutter_callkit_incoming: ^2.0.0
  ethereum_addresses: ^1.0.2
  widget_circular_animator: ^1.0.0
  flutter_badged: ^2.0.3
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.1.1
  defer_pointer: ^0.0.2
  flutter_slidable: ^2.0.0
  story_view: ^0.14.0
  stop_watch_timer: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.4.43
  highlight_text: ^1.6.0
  camera: ^0.10.1
  video_trimmer: ^2.0.0
  ndialog: ^4.2.3
  path: ^1.8.0
  launch_review: ^3.0.1
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  hex: ^0.2.0
  qr_code_scanner: ^1.0.1
  record: ^4.4.4
  just_audio: ^0.9.31
  firebase_dynamic_links: ^5.1.1
  flutter_typeahead: ^4.3.7
  flutter_beep: ^1.0.0
  walletconnect_flutter_v2: ^2.0.12
  stream_chat_persistence: ^6.1.0
  web_socket_channel: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/chat_tab.png
     - assets/images/group-tab.png
     - assets/images/home_tab.png
     - assets/images/profile_tab.png
     - assets/images/call_tab.png
     - assets/images/people.png
     - assets/images/wallet.png
     - assets/images/empty_box.png
     - assets/images/logo.svg
     - assets/images/arrow_left.png
     - assets/images/more.png
     - assets/images/bell.png
     - assets/images/plus.png
     - assets/images/arrow_down.png
     - assets/images/arrow_up.png
     - assets/images/arrow_up_rev.png
     - assets/images/arrow_down_rev.png
     - assets/images/search.png
     - assets/images/outgoing.png
     - assets/images/incoming.png
     - assets/images/missed.png
     - assets/images/logo.png
     - assets/images/close.png
     - assets/images/close_big.png
     - assets/images/send.png
     - assets/images/done.png
     - assets/images/edit.png
     - assets/images/add_user.png
     - assets/images/validation.png
     - assets/images/screenshot.png
     - assets/images/share.png
     - assets/images/write.png
     - assets/images/copy.png
     - assets/images/app_icon.png
     - assets/images/giphy_icon.png
     - assets/images/placeholder.png
     - assets/images/app_icon_rounded.png
     - assets/images/stories.png
     - assets/images/chat_missed.png
     - assets/images/group_chat_missed.png
     - assets/images/align_center.png
     - assets/images/align_left.png
     - assets/images/align_rigth.png
     - assets/images/arrow.png
     - assets/images/brush.png
     - assets/images/check.png
     - assets/images/circular_gradient.png
     - assets/images/colorpalette.png
     - assets/images/download.png
     - assets/images/draft.png
     - assets/images/draw.png
     - assets/images/font_backGround.png
     - assets/images/marker.png
     - assets/images/neon.png
     - assets/images/pen.png
     - assets/images/pickColor.png
     - assets/images/return.png
     - assets/images/stickers.png
     - assets/images/text.png
     - assets/images/trash.png
     - assets/images/photo_filter.png
     - assets/images/video_trim.png
     - assets/images/instagram_logo.png
     - assets/images/micro.svg
     - assets/images/volume.svg
     - assets/images/call_end.svg
     - assets/images/metamask.png
     - assets/images/qrcode.png
     - assets/images/admin.png
     - assets/images/ethereum.png
     - assets/images/logo_light_theme.png
     - assets/images/logo_dark_theme.png
     - assets/pdf/tc.pdf
     - assets/pdf/pp.pdf
     - assets/pdf/all.pdf
     - animations/
     - svgs/
     - lib/svgs/
     - assets/ca/
     - assets/abi.json

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900