name: sirkl
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_portal: ^1.0.0
  http: ^0.13.4
  http_parser: ^4.0.0
  image_gallery_saver: 1.7.0
  image_picker: ^0.8.6
  jiffy: ^5.0.0
  lottie: ^1.0.1
  meta: ^1.3.0
  path_provider: ^2.0.9
  photo_manager: ^2.0.1
  photo_view: ^0.14.0
  rxdart: ^0.27.0
  share_plus: ^4.5.0
  shimmer: ^2.0.0
  stream_chat_flutter_core: ^5.2.0
  synchronized: ^3.0.0
  thumblr: ^0.0.4
  video_player: ^2.4.5
  video_player_macos: ^1.0.6
  video_thumbnail: ^0.5.0
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  get_storage: ^2.0.3
  nice_buttons: ^0.0.2
  flutter_svg: ^1.1.5
  wallet_connect: ^1.0.2
  material_floating_search_bar: ^0.3.7
  flutter_chat_ui: ^1.6.4
  azlistview: ^2.0.0
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.5
  firebase_core: ^1.23.0
  firebase_messaging: ^13.0.3
  images_picker: ^1.2.11
  simple_s3: ^0.3.2
  cached_network_image: ^3.2.2
  infinite_scroll_pagination: ^3.2.0
  timeago: ^3.3.0
  bip39: ^1.0.6
  intl: ^0.17.0
  tiny_avatar: ^0.0.3
  chewie: ^1.3.4
  collection: ^1.15.0
  contextmenu: ^3.0.0
  dart_vlc: ^0.3.0
  desktop_drop: ^0.3.3
  diacritic: ^0.1.3
  dio: ^4.0.6
  ezanimation: ^0.6.0
  file_picker: ^4.1.3
  file_selector: ^0.9.0
  image_downloader: ^0.31.0
  web3dart: ^2.4.1
  slider_button: ^2.0.0
  agora_rtc_engine: ^5.3.1
  permission_handler: ^9.2.0
  flutter_callkit_incoming: ^1.0.3+1
  ethereum_addresses: ^1.0.2
  widget_circular_animator: ^1.0.0
  flutter_badged: ^2.0.3
  flutter_local_notifications: ^12.0.4
  modal_gif_picker: ^0.0.2
  perfect_freehand: ^1.0.4
  align_positioned: ^3.0.0
  fluttertoast: ^8.1.1
  animated_text_kit: ^4.2.2
  flutter_screenutil: ^5.6.0
  gallery_media_picker: ^0.0.82
  defer_pointer: ^0.0.2
  flutter_slidable: ^2.0.0
  story_view: ^0.14.0
  story: ^0.8.0
  stop_watch_timer: ^2.0.0
  persistent_bottom_nav_bar_v2: ^4.2.6

dev_dependencies:
  dart_code_metrics: ^4.4.0
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0
  path: ^1.8.0
  flutter_launcher_icons: "^0.10.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
     - assets/images/chat_tab.png
     - assets/images/group-tab.png
     - assets/images/home_tab.png
     - assets/images/profile_tab.png
     - assets/images/call_tab.png
     - assets/images/people.png
     - assets/images/wallet.png
     - assets/images/empty_box.png
     - assets/images/logo.svg
     - assets/images/arrow_left.png
     - assets/images/more.png
     - assets/images/bell.png
     - assets/images/plus.png
     - assets/images/arrow_down.png
     - assets/images/arrow_up.png
     - assets/images/arrow_up_rev.png
     - assets/images/arrow_down_rev.png
     - assets/images/search.png
     - assets/images/outgoing.png
     - assets/images/incoming.png
     - assets/images/missed.png
     - assets/images/logo.png
     - assets/images/close.png
     - assets/images/close_big.png
     - assets/images/send.png
     - assets/images/done.png
     - assets/images/edit.png
     - assets/images/add_user.png
     - assets/images/validation.png
     - assets/images/screenshot.png
     - assets/images/share.png
     - assets/images/write.png
     - assets/images/copy.png
     - assets/images/app_icon.png
     - assets/images/giphy_icon.png
     - assets/images/placeholder.png
     - assets/images/app_icon_rounded.png
     - assets/images/stories.png
     - assets/images/chat_missed.png
     - assets/images/group_chat_missed.png
     - assets/images/align_center.png
     - assets/images/align_left.png
     - assets/images/align_rigth.png
     - assets/images/arrow.png
     - assets/images/brush.png
     - assets/images/check.png
     - assets/images/circular_gradient.png
     - assets/images/colorpalette.png
     - assets/images/download.png
     - assets/images/draft.png
     - assets/images/draw.png
     - assets/images/font_backGround.png
     - assets/images/marker.png
     - assets/images/neon.png
     - assets/images/pen.png
     - assets/images/pickColor.png
     - assets/images/return.png
     - assets/images/stickers.png
     - assets/images/text.png
     - assets/images/trash.png
     - assets/images/photo_filter.png
     - assets/images/video_trim.png
     - assets/images/instagram_logo.png
     - assets/images/micro.svg
     - assets/images/volume.svg
     - assets/images/call_end.svg
     - animations/
     - svgs/
     - lib/svgs/
     - assets/ca/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-VariableFont_wght.ttf

    - family: B612
      fonts:
        - asset: assets/fonts/B612-Regular.ttf

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf

    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf

    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-Regular.ttf

    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf

    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf

    - family: YatraOne
      fonts:
        - asset: assets/fonts/YatraOne-Regular.ttf

    - family: OldStandardTT
      fonts:
        - asset: assets/fonts/OldStandardTT-Italic.ttf

    - family: Neonderthaw
      fonts:
        - asset: assets/fonts/Neonderthaw-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: SedgwickAve
      fonts:
        - asset: assets/fonts/SedgwickAve-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf

    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf

    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

    - family: FrederickatheGreat
      fonts:
        - asset: assets/fonts/FrederickatheGreat-Regular.ttf

    - family: ReenieBeanie
      fonts:
        - asset: assets/fonts/ReenieBeanie-Regular.ttf

    - family: BungeeShade
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf

    - family: UnifrakturMaguntia
      fonts:
        - asset: assets/fonts/UnifrakturMaguntia-Regular.ttf
