name: sirkl
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  get_storage: ^2.0.3
  nice_buttons: ^0.0.2
  flutter_svg: ^1.1.5
  wallet_connect: ^1.0.2
  material_floating_search_bar: ^0.3.7
  flutter_chat_ui: ^1.6.4
  azlistview: ^2.0.0
  advstory: ^0.2.1
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.5
  firebase_core: ^1.23.0
  firebase_messaging: ^13.0.3
  images_picker: ^1.2.11
  simple_s3: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.2
  zego_zim: ^2.4.0
  infinite_scroll_pagination: ^3.2.0
  timeago: ^3.3.0
  bip39: ^1.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/chat_tab.png
     - assets/images/group-tab.png
     - assets/images/home_tab.png
     - assets/images/profile_tab.png
     - assets/images/call_tab.png
     - assets/images/people.png
     - assets/images/wallet.png
     - assets/images/empty_box.png
     - assets/images/logo.svg
     - assets/images/arrow_left.png
     - assets/images/more.png
     - assets/images/bell.png
     - assets/images/plus.png
     - assets/images/arrow_down.png
     - assets/images/arrow_up.png
     - assets/images/arrow_up_rev.png
     - assets/images/arrow_down_rev.png
     - assets/images/search.png
     - assets/images/outgoing.png
     - assets/images/incoming.png
     - assets/images/missed.png
     - assets/images/logo.png
     - assets/images/close.png
     - assets/images/close_big.png
     - assets/images/send.png
     - assets/images/done.png
     - assets/images/edit.png
     - assets/images/add_user.png
     - assets/images/validation.png
     - assets/images/screenshot.png
     - assets/images/share.png
     - assets/images/write.png
     - assets/images/copy.png

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
