// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0hgHqLsgT4mIirnYfEAjXLuWI_pCx-rw',
    appId: '1:208005039506:web:ffc07bad1b4483b7892d4b',
    messagingSenderId: '208005039506',
    projectId: 'sirkl-e138d',
    authDomain: 'sirkl-e138d.firebaseapp.com',
    storageBucket: 'sirkl-e138d.appspot.com',
    measurementId: 'G-ZTK2PHZTE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqK0bZj-qbKDkjC2jH_RLKNfpnAI3_DP8',
    appId: '1:208005039506:android:043d322518f49448892d4b',
    messagingSenderId: '208005039506',
    projectId: 'sirkl-e138d',
    storageBucket: 'sirkl-e138d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWNceyM6Znr3FxQmXpRE1r_ac00SlTbs8',
    appId: '1:208005039506:ios:8b152ba0215b7dcd892d4b',
    messagingSenderId: '208005039506',
    projectId: 'sirkl-e138d',
    storageBucket: 'sirkl-e138d.appspot.com',
    iosClientId: '208005039506-v8hdtf1gq1hkbs58l6hsiui8kfbprqfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirkl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWNceyM6Znr3FxQmXpRE1r_ac00SlTbs8',
    appId: '1:208005039506:ios:8b152ba0215b7dcd892d4b',
    messagingSenderId: '208005039506',
    projectId: 'sirkl-e138d',
    storageBucket: 'sirkl-e138d.appspot.com',
    iosClientId: '208005039506-v8hdtf1gq1hkbs58l6hsiui8kfbprqfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirkl',
  );
}
